<?xml version="1.0" encoding="utf-8"?>
<AddOnRegData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" SlientInstallation="No" SlientUpgrade="No" Partnernmsp="ERPBOTHUB" SchemaVersion="3.0" Type="" MultipleVersion="true" OnDemand="" OnPremise="" ExtName="EBHMaterialPlanning" ExtVersion="1.0.1" Contdata="EBH Team" Partner="ERPBOTHUB" DBType="Both" ClientType="A">
  <Validity>
    <SBOCompatibility>
      <Version From="" To="" />
    </SBOCompatibility>
  </Validity>
  <Configuration>
    <Repository>
      <Properties />
    </Repository>
    <Deployment>
      <Properties />
    </Deployment>
    <Assignment>
      <Properties />
    </Assignment>
  </Configuration>
  <Addons>
    <Addon Name="" Group="" ForceFlag="" Visible="" AutoAssign="" SelfUpgrd="">
      <x86 AddonExe="C:\Users\rajaram\Desktop\ACPL LLP\EBH Material Planning\EBHMaterialPlanning\bin\x64\Debug\EBHMaterialPlanning.exe" AddonSig="">
        <Installation>
          <Files>
            <File FileName="EBHMaterialPlanning.b1s">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.exe">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.exe.config">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.pdb">
              <Actions />
            </File>
            <File FileName="ERPBotHubDLL.dll">
              <Actions />
            </File>
            <File FileName="Menu.png">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneLicense.dll">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneSDK.dll">
              <Actions />
            </File>
          </Files>
        </Installation>
        <Uninstallation>
          <Files>
            <File FileName="EBHMaterialPlanning.b1s">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.exe">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.exe.config">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.pdb">
              <Actions />
            </File>
            <File FileName="ERPBotHubDLL.dll">
              <Actions />
            </File>
            <File FileName="Menu.png">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneLicense.dll">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneSDK.dll">
              <Actions />
            </File>
          </Files>
        </Uninstallation>
      </x86>
      <x64 AddonExe="C:\Users\rajaram\Desktop\ACPL LLP\EBH Material Planning\EBHMaterialPlanning\bin\x64\Debug\EBHMaterialPlanning.exe" AddonSig="">
        <Installation>
          <Files>
            <File FileName="EBHMaterialPlanning.b1s">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.exe">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.exe.config">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.pdb">
              <Actions />
            </File>
            <File FileName="ERPBotHubDLL.dll">
              <Actions />
            </File>
            <File FileName="Menu.png">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneLicense.dll">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneSDK.dll">
              <Actions />
            </File>
          </Files>
        </Installation>
        <Uninstallation>
          <Files>
            <File FileName="EBHMaterialPlanning.b1s">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.exe">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.exe.config">
              <Actions />
            </File>
            <File FileName="EBHMaterialPlanning.pdb">
              <Actions />
            </File>
            <File FileName="ERPBotHubDLL.dll">
              <Actions />
            </File>
            <File FileName="Menu.png">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneLicense.dll">
              <Actions />
            </File>
            <File FileName="SAPBusinessOneSDK.dll">
              <Actions />
            </File>
          </Files>
        </Uninstallation>
      </x64>
    </Addon>
  </Addons>
  <XApps>
    <XApp Name="" Path="" FileName="" />
  </XApps>
  <UDQs>
    <UDQ udqname="">
      <Hana FileName="" />
    </UDQ>
  </UDQs>
</AddOnRegData>