# Builds <AssemblyName>.b1s (the form bundle SAPbouiCOM.Framework loads at run time) from the project's .b1f files.
# SAP Business One Studio writes this file when it is active in Visual Studio; a command-line build does not,
# so the project calls this script after every build.
#
# The bundle holds every form twice:
#   project type "Add-on"   : the .b1f as designed (used by B1 Studio)
#   project type "VSIBuilt" : the same form converted to UI API XML (<Application><forms><action type="add"><form ...>),
#                             which is what UserFormBase loads. A raw .b1f here makes the form constructor fail
#                             with a NullReferenceException in Application.UserFormLoadBatchAction.
#
# The converter covers what this add-on's forms use: form header, user data sources and button items.
# A form with anything else stops the build with a message instead of producing a bundle that fails at run time.
param([string]$ProjectDir, [string]$OutFile, [string]$ProjectGuid)
$ErrorActionPreference = "Stop"

function Esc([string]$v) { [System.Security.SecurityElement]::Escape($v) }
function Bit([string]$v) { if ($v -eq "True") { "1" } else { "0" } }

function Convert-Form([string]$path) {
    [xml]$doc = [System.IO.File]::ReadAllText($path)
    $f = $doc.form
    $name = [System.IO.Path]::GetFileName($path)
    function A($node, [string]$attr) { Esc($node.GetAttribute($attr)) }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append('<?xml version="1.0" encoding="UTF-16"?><Application><forms><action type="add">')
    [void]$sb.Append('<form appformnumber="-1" FormType="' + (A $f FormType) + '" type="' + (A $f BorderStyle) + '" BorderStyle="' + (A $f BorderStyle) +
        '" uid="' + (A $f UniqueID) + '" title="' + (A $f Title) + '" visible="' + (Bit $f.GetAttribute("Visible")) + '" default_button="' + (A $f DefaultButton) +
        '" pane="' + (A $f Pane) + '" color="' + (A $f Color) + '" left="' + (A $f Left) + '" top="' + (A $f Top) + '" width="' + (A $f Width) + '" height="' + (A $f Height) +
        '" client_width="' + (A $f Client_Width) + '" client_height="' + (A $f Client_Height) + '" AutoManaged="' + (Bit $f.GetAttribute("AutoManaged")) +
        '" SupportedModes="15" ObjectType="' + (A $f ObjectType) + '" mode="' + (A $f Mode) + '">')

    # Data sources: only user data sources are supported
    foreach ($n in $f.SelectNodes("datasources/*")) {
        if ($n.Name -ne "userdatasources" -and $n.HasChildNodes) { throw "$name : <$($n.Name)> is not supported by tools\MakeB1s.ps1. Build this form with SAP Business One Studio." }
    }
    [void]$sb.Append('<datasources><DataTables /><dbdatasources><action type="add" /></dbdatasources><userdatasources>')
    $uds = $f.SelectNodes("datasources/userdatasources/datasource")
    if ($uds.Count -eq 0) { [void]$sb.Append('<action type="add" />') }
    else {
        [void]$sb.Append('<action type="add">')
        foreach ($d in $uds) { [void]$sb.Append('<datasource type="' + (A $d Type) + '" size="' + (A $d Size) + '" uid="' + (A $d UniqueID) + '" />') }
        [void]$sb.Append('</action>')
    }
    [void]$sb.Append('</userdatasources></datasources><Menus />')

    # Items: buttons (type 4) with a caption
    $items = $f.SelectNodes("item")
    if ($items.Count -eq 0) { [void]$sb.Append('<items><action type="add" /></items>') }
    else {
        [void]$sb.Append('<items><action type="add">')
        foreach ($i in $items) {
            if ($i.GetAttribute("Type") -ne "4") { throw "$name : item '$($i.GetAttribute("UniqueID"))' has type $($i.GetAttribute("Type")); only buttons (type 4) are supported by tools\MakeB1s.ps1. Build this form with SAP Business One Studio." }
            [void]$sb.Append('<item top="' + (A $i Top) + '" left="' + (A $i Left) + '" width="' + (A $i Width) + '" height="' + (A $i Height) +
                '" AffectsFormMode="' + (Bit $i.GetAttribute("AffectsFormMode")) + '" description="' + (A $i Description) + '" disp_desc="' + (Bit $i.GetAttribute("DisplayDesc")) +
                '" enabled="' + (Bit $i.GetAttribute("Enabled")) + '" from_pane="' + (A $i FromPane) + '" to_pane="' + (A $i ToPane) + '" linkto="' + (A $i LinkTo) +
                '" right_just="' + (Bit $i.GetAttribute("RightJustified")) + '" type="' + (A $i Type) + '" visible="' + (Bit $i.GetAttribute("Visible")) +
                '" uid="' + (A $i UniqueID) + '" IsAutoGenerated="' + (Bit $i.GetAttribute("IsAutoGenerated")) + '"><specific caption="' + (A $i.SelectSingleNode("specific") Caption) + '" /></item>')
        }
        [void]$sb.Append('</action></items>')
    }
    foreach ($n in $f.ChildNodes) {
        if ($n.NodeType -eq "Element" -and @("datasources", "item", "FormCategory") -notcontains $n.Name) { throw "$name : <$($n.Name)> is not supported by tools\MakeB1s.ps1. Build this form with SAP Business One Studio." }
    }

    [void]$sb.Append('<ChooseFromListCollection><action type="add"><ChooseFromList UniqueID="-1" ObjectType="-1" MultiSelection="0" IsSystem="1" /></action></ChooseFromListCollection>')
    [void]$sb.Append('<DataBrowser BrowseBy="' + (A $f BrowseBy) + '" /><Settings MatrixUID="' + (A $f Settings_GridItemUID) + '" Enabled="' + (Bit $f.GetAttribute("Enabled")) +
        '" EnableRowFormat="' + (Bit $f.GetAttribute("EnableRowFormat")) + '" /></form></action></forms></Application>')
    $sb.ToString()
}

$forms = Get-ChildItem -Path $ProjectDir -Recurse -Filter *.b1f | Where-Object { $_.FullName -notmatch '\\(bin|obj)\\' } | Sort-Object FullName
$settings = New-Object System.Xml.XmlWriterSettings
$settings.Indent = $true
$settings.Encoding = [System.Text.Encoding]::Unicode
$writer = [System.Xml.XmlWriter]::Create($OutFile, $settings)
try {
    $writer.WriteStartDocument($true)
    $writer.WriteStartElement("projects")
    foreach ($project in @(@{ name = $ProjectGuid.ToLower(); type = "Add-on" }, @{ name = "VSIcreated"; type = "VSIBuilt" })) {
        $writer.WriteStartElement("project")
        $writer.WriteAttributeString("name", $project.name)
        $writer.WriteAttributeString("type", $project.type)
        foreach ($form in $forms) {
            $writer.WriteStartElement("file")
            $writer.WriteAttributeString("name", $form.FullName.Substring($ProjectDir.TrimEnd('\').Length + 1).Replace('\', '/'))
            $writer.WriteAttributeString("type", "UserForm")
            if ($project.type -eq "Add-on") {
                $writer.WriteAttributeString("time", $form.LastWriteTime.ToString("dd-MM-yyyy HH:mm:ss"))
                $content = [System.IO.File]::ReadAllText($form.FullName)
            }
            else { $content = Convert-Form $form.FullName }
            $writer.WriteStartElement("content")
            $writer.WriteAttributeString("desc", $content)
            $writer.WriteEndElement()
            $writer.WriteEndElement()
        }
        $writer.WriteEndElement()
    }
    $writer.WriteEndElement()
    $writer.WriteEndDocument()
}
finally { $writer.Close() }
Write-Host "b1s: $($forms.Count) form(s) -> $OutFile"
